# Site
name: "GDSC UOS"
description: "GDSC UOS 블로그입니다."

baseurl:
include: ["_pages"]
permalink: /:title/

logo: 'assets/images/dsclogo.png'
full_logo: 'assets/images/dsc_full_logo.png'
google_analytics: 'UA-179269963-1'
disqus: 'dscuos'

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed

# Pagination
paginate: 12
paginate_path: /page:num/

# Other
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude:
  - Gemfile
  - Gemfile.lock
  - .vscode
  - .git
  - .gitignore
  - .DS_Store
  - CONTRIBUTING.md

# MathJax
lsi: false
excerpt_separator: "\n\n"
incremental: false