version: '3.2'

services:
    jekyll:
        image: jekyll/jekyll:4.2.0
        command: jekyll serve --force_polling
        ports:
            - 4000:4000
        volumes:
            - .:/srv/jekyll